config/routes.rb
Workarea::Admin::Engine.routes.draw do
  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    resources :payment_gift_cards do
      get :redemptions
    end
  end
end

Workarea::Storefront::Engine.routes.draw do
  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    get 'gift_cards/balance', to: 'gift_cards#index'
    get 'gift_cards/lookup', to: 'gift_cards#lookup'

    namespace :checkout do
      patch 'gift_cards', to: 'gift_cards#add'
      delete 'gift_cards', to: 'gift_cards#remove'
    end
  end
end

if Workarea::Plugin.installed?(:api)
  Workarea::Api::Admin::Engine.routes.draw do
    resources :gift_cards do
      collection { patch 'bulk' }
    end
  end

  Workarea::Api::Storefront::Engine.routes.draw do
    resources :checkouts, only: [] do
      member do
        patch 'add_gift_card'
        delete 'remove_gift_card'
      end
    end

    get 'gift_cards/balance', to: 'gift_cards#balance'
  end
end

app/views/workarea/admin/activities/_payment_gift_card_create.html.haml
.activity
  .activity__header
    .activity__avatar
      = link_to_modifier(entry) do
        = avatar_for entry.modifier
    %h3.activity__name= link_to_modifier(entry)
    %p.activity__time= activity_time(entry.created_at)
  .activity__message
    - if entry.audited.present?
      = t('workarea.admin.activities.payment_gift_card_create_html', name: link_to(entry.audited.name, payment_gift_card_path(entry.audited)))
    - else
      = t('workarea.admin.activities.payment_gift_card_create_html', name: t('workarea.payment_gift_card.name', token: entry.token))

app/views/workarea/admin/activities/_payment_gift_card_destroy.html.haml
.activity
  .activity__header
    .activity__avatar
      = link_to_modifier(entry) do
        = avatar_for entry.modifier
    %h3.activity__name= link_to_modifier(entry)
    %p.activity__time= activity_time(entry.created_at)
  .activity__message
    = t('workarea.admin.activities.payment_gift_card_destroy_html')
    = link_to_restore_for(entry)

app/views/workarea/admin/activities/_payment_gift_card_update.html.haml
.activity
  .activity__header
    .activity__avatar
      = link_to_modifier(entry) do
        = avatar_for entry.modifier
    %h3.activity__name= link_to_modifier(entry)
    %p.activity__time= activity_time(entry.created_at)
  .activity__message
    - if entry.audited.blank?
      - name = t('workarea.payment_gift_card.name', token: entry.token)
    - else
      - name = link_to(entry.audited.name, payment_gift_card_path(entry.audited))

    = t('workarea.admin.activities.payment_gift_card_update_html', fields: fields_clause_for(entry.tracked_changes), name: name)