config/routes.rb
Workarea::Admin::Engine.routes.draw do
  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    resources :payment_gift_cards do
      get :redemptions
    end
  end
end

Workarea::Storefront::Engine.routes.draw do
  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    get 'gift_cards/balance', to: 'gift_cards#index'
    get 'gift_cards/lookup', to: 'gift_cards#lookup'

    namespace :checkout do
      patch 'gift_cards', to: 'gift_cards#add'
      delete 'gift_cards', to: 'gift_cards#remove'
    end
  end
end

if Workarea::Plugin.installed?(:api)
  Workarea::Api::Admin::Engine.routes.draw do
    resources :gift_cards do
      collection { patch 'bulk' }
    end
  end

  Workarea::Api::Storefront::Engine.routes.draw do
    resources :checkouts, only: [] do
      member do
        patch 'add_gift_card'
        delete 'remove_gift_card'
      end
    end

    get 'gift_cards/balance', to: 'gift_cards#balance'
  end
end

app/models/workarea/checkout/steps/gift_card.rb
module Workarea
  class Checkout
    module Steps
      class GiftCard < Base
        # Add a gift card tender to the order, updates pricing and adjusts the
        # tender amounts for all existing tenders.
        #
        # @param [Hash] params
        # @option params [String] :gift_card_number a gift card number to apply
        #
        # @return [Boolean] whether the update succeeded (payment were saved)
        #
        def update(params = {})
          gift_card_params = extract_gift_card_params(params)

          add_gift_card(gift_card_params) if applicable_gift_card?(gift_card_params)

          update_order
        end

        # Removes a gift card from payment, updates order pricing and readjusts
        # tender amounts.
        #
        # @param [String] id the gift card tender id
        #
        # @return [Boolean] whether the update succeeded (payment was saved)
        #
        def remove(id)
          payment.gift_cards.find(id).destroy
        rescue Mongoid::Errors::DocumentNotFound
          # no op
        ensure
          update_order
        end

        # Whether this step of checkout is considered complete. Requires either
        # no gift cards applied, or that all gift cards are valid with a
        # balance. No balance could mean a card is expired, or has been used.
        #
        # @return [Boolean]
        #
        def complete?
          !payment.gift_card? ||
            (
              payment.gift_cards.all?(&:valid?) &&
              payment.gift_cards.none? { |g| g.balance.zero? }
            )
        end

        private

        def extract_gift_card_params(params)
          { number: params[:gift_card_number].to_s.gsub(/\s+/, '') }
        end

        def applicable_gift_card?(params)
          return false unless params[:number].present?
          Workarea::GiftCards.gateway.balance(params[:number]) > 0
        end

        def add_gift_card(params)
          payment.add_gift_card(params)
        end

        def update_order
          Pricing.perform(order, shippings)
          payment.adjust_tender_amounts(order.total_price)
        end
      end
    end
  end
end

app/controllers/workarea/api/storefront/gift_cards_controller.rb
module Workarea
  if Plugin.installed?(:api)
    module Api
      module Storefront
        class GiftCardsController < Api::Storefront::ApplicationController
          def balance
            @gift_card = Workarea::GiftCards.gateway.lookup(params)

            if @gift_card.blank?
              raise Mongoid::Errors::DocumentNotFound.new(
                Payment::GiftCard,
                params.to_unsafe_h.except('controller', 'action')
              )
            end
          end
        end
      end
    end
  end
end

app/controllers/workarea/storefront/checkout/gift_cards_controller.rb
module Workarea
  module Storefront
    module Checkout
      class GiftCardsController < CheckoutsController
        def add
          step = Workarea::Checkout::Steps::GiftCard.new(current_checkout)

          if step.update(params)
            flash[:success] = t('workarea.storefront.flash_messages.gift_card_added')
            redirect_to checkout_payment_path
          else
            @step = Storefront::Checkout::PaymentViewModel.new(
              step,
              view_model_options
            )

            flash[:error] = t('workarea.storefront.flash_messages.gift_card_error')
            render :payment
          end
        end

        def remove
          step = Workarea::Checkout::Steps::GiftCard.new(current_checkout)
          step.remove(params[:gift_card_id])

          flash[:success] = t('workarea.storefront.flash_messages.gift_card_removed')
          redirect_to checkout_payment_path
        end
      end
    end
  end
end

app/controllers/workarea/storefront/gift_cards_controller.rb
module Workarea
  module Storefront
    class GiftCardsController < ApplicationController
      def index
      end

      def lookup
        gift_card = Workarea::GiftCards.gateway.lookup(params)

        if gift_card.present?
          flash[:success] = t(
            'workarea.storefront.flash_messages.gift_card_balance',
            balance: gift_card.balance.format
          )
        else
          flash[:error] = t('workarea.storefront.flash_messages.gift_card_not_found')
        end

        redirect_to gift_cards_balance_path
      end
    end
  end
end

app/views/workarea/storefront/checkouts/_gift_card_error.html.haml
- if step.gift_card?
  - step.gift_cards.each do |gift_card|
    - if gift_card.errors.any?
      - gift_card.full_messages.each do |message|
        .message.message--error
          %p.message__type
            %span.message__icon= t('workarea.storefront.messages.error')
          %p.message__text= message

app/views/workarea/storefront/checkouts/_gift_card_payment.html.haml
.checkout-payment__secondary-method{ class: step.gift_card? ? 'checkout-payment__secondary-method--visible' : nil }

  - if step.gift_card?
    .message.message--info
      %p.message__type
        %span.message__icon= t('workarea.storefront.messages.info')
      %p.message__text
        #{t('workarea.storefront.gift_cards.balance_html', amount: number_to_currency(step.gift_card_balance))}
        #{t('workarea.storefront.gift_cards.applied_to_order_html', amount: number_to_currency(step.gift_card_amount))}

        - if step.tender_required?
          #{t('workarea.storefront.gift_cards.tender_required_html', amount: number_to_currency(step.order_balance))}
        - else
          #{t('workarea.storefront.gift_cards.place_order')}

  = optional_field(t('workarea.storefront.gift_cards.enter_gift_card_prompt'), step.gift_cards, step.failed_gift_card) do

    %h2= t('workarea.storefront.gift_cards.gift_card')

    = form_tag checkout_gift_cards_path, method: 'patch', id: 'gift_card_form', class: 'inline-form' do

      .inline-form__cell
        .value
          = text_field_tag 'gift_card_number', step.failed_gift_card&.number, class: 'text-box', autocomplete: 'off', title: t('workarea.storefront.gift_cards.gift_card_number'), placeholder: t('workarea.storefront.gift_cards.gift_card_number')
          - if step.failed_gift_card && step.failed_gift_card.errors[:number].present?
            %span.value__error= step.failed_gift_card.errors[:number].first
      .inline-form__cell
        %p= button_tag t('workarea.storefront.gift_cards.apply_gift_card'), value: 'apply_gift_card', class: 'button'

    .applied-gift-cards
      - step.gift_cards.each do |gift_card|
        %p.applied-gift-card
          %strong.applied-gift-card__number= gift_card.display_number
          = link_to t('workarea.storefront.gift_cards.remove'), checkout_gift_cards_path(gift_card_id: gift_card.id), data: { method: :delete, confirm: t('workarea.storefront.gift_cards.remove_confirmation') }, class: 'applied-gift-card__remove-link'
          %br
          %span.applied-gift-card__applied= t('workarea.storefront.gift_cards.balance_applied_html', amount: number_to_currency(gift_card.amount), balance: number_to_currency(gift_card.balance))

app/views/workarea/storefront/checkouts/_gift_card_summary.html.haml
- if summary.gift_card?
  %tr
    %th
      %span= t('workarea.storefront.gift_cards.gift_card')
    %td
      %strong.table__price-discount −#{number_to_currency(summary.gift_card_amount)}