config/routes.rb
Workarea::Admin::Engine.routes.draw do
  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    resources :payment_gift_cards do
      get :redemptions
    end
  end
end

Workarea::Storefront::Engine.routes.draw do
  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    get 'gift_cards/balance', to: 'gift_cards#index'
    get 'gift_cards/lookup', to: 'gift_cards#lookup'

    namespace :checkout do
      patch 'gift_cards', to: 'gift_cards#add'
      delete 'gift_cards', to: 'gift_cards#remove'
    end
  end
end

if Workarea::Plugin.installed?(:api)
  Workarea::Api::Admin::Engine.routes.draw do
    resources :gift_cards do
      collection { patch 'bulk' }
    end
  end

  Workarea::Api::Storefront::Engine.routes.draw do
    resources :checkouts, only: [] do
      member do
        patch 'add_gift_card'
        delete 'remove_gift_card'
      end
    end

    get 'gift_cards/balance', to: 'gift_cards#balance'
  end
end

app/models/workarea/search/admin/payment_gift_card.rb
module Workarea
  module Search
    class Admin
      class PaymentGiftCard < Search::Admin
        def type
          'gift_card'
        end

        def search_text
          [
            model.token,
            model.to,
            model.from,
            model.message
          ].join ' '
        end

        def jump_to_text
          "#{model.token} - balance: #{model.balance}"
        end

        def status
          if model.balance.zero?
            'redeemed'
          elsif model.used > 0
            'partially_redeemed'
          else
            'unredeemed'
          end
        end

        def created_by
          if model.order_id.present?
            'order'
          else
            'admin'
          end
        end

        def facets
          super.merge(created_by: created_by)
        end
      end
    end
  end
end

app/controllers/workarea/admin/payment_gift_cards_controller.rb
module Workarea
  module Admin
    class PaymentGiftCardsController < Admin::ApplicationController
      required_permissions :orders
      before_action :find_gift_card, except: :index

      def index
        search = Search::AdminGiftCards.new(params)
        @search = Admin::SearchViewModel.new(search, view_model_options)
      end

      def show; end

      def new; end

      def create
        if @gift_card.save
          flash[:success] = 'Gift card has been created.'
          redirect_to payment_gift_card_path(@gift_card)
        else
          render :new
        end
      end

      def edit; end

      def update
        if @gift_card.update_attributes(gift_card_params)
          flash[:success] = 'Gift card has been saved.'
          redirect_to payment_gift_card_path(@gift_card)
        else
          render :edit
        end
      end

      def destroy
        @gift_card.destroy
        flash[:success] = "Gift card #{@gift_card.token} has been removed."
        redirect_to payment_gift_cards_path
      end

      def redemptions
      end

      private

      def find_gift_card
        gift_card =
          if params[:id].present?
            Payment::GiftCard.find(params[:id])
          elsif params[:payment_gift_card_id].present?
            Payment::GiftCard.find(params[:payment_gift_card_id])
          else
            Payment::GiftCard.new(gift_card_params)
          end

        @gift_card =
          Admin::PaymentGiftCardViewModel.new(
            gift_card,
            view_model_options
          )
      end

      def gift_card_params
        return {} if params[:gift_card].blank?
        params[:gift_card].permit(
          :token,
          :to,
          :from,
          :message,
          :expires_at,
          :amount,
          :notify
        )
      end
    end
  end
end

app/views/workarea/admin/payment_gift_cards/_aux_navigation.html.haml
- if model.order_id
  .grid.grid--auto.grid--right.grid--middle
    .grid__cell
      = link_to t('workarea.admin.payment_gift_cards.view_order'), order_path(model.order_id)

app/views/workarea/admin/payment_gift_cards/_cards.html.haml
.grid.grid--auto.grid--flush.grid--center
  .grid__cell
    .card{ class: card_classes(:attributes, local_assigns[:active]) }
      = link_to edit_payment_gift_card_path(model), class: 'card__header' do
        %span.card__header-text= t('workarea.admin.cards.attributes.title')
        = inline_svg 'workarea/admin/icons/attributes.svg', class: 'card__icon'

      - if local_assigns[:active].blank?
        .card__body
          %ul.list-reset
            %li
              %strong #{t('workarea.admin.fields.token')}:
              = model.token
            %li
              %strong #{t('workarea.admin.fields.amount')}:
              = number_to_currency model.amount
            %li
              %strong #{t('workarea.admin.fields.order_id')}:
              = model.order_id.presence || t('workarea.admin.cards.attributes.no_value')
            %li
              %strong #{t('workarea.admin.fields.recipient')}:
              = model.to
            %li
              %strong #{t('workarea.admin.fields.from')}:
              = model.from.presence || t('workarea.admin.cards.attributes.no_value')
            %li
              %strong #{t('workarea.admin.fields.message')}:
              = model.message.presence || t('workarea.admin.cards.attributes.no_value')
            %li
              %strong #{t('workarea.admin.fields.notify')}:
              = model.notify ? t('workarea.admin.true') : t('workarea.admin.false')
            %li
              %strong #{t('workarea.admin.fields.expires_at')}:
              - if model.expires_at.present?
                = local_time_ago(model.expires_at)
              - else
                = t('workarea.admin.cards.attributes.no_value')
            %li
              %strong= t('workarea.admin.fields.updated_at')
              #{local_time_ago(model.updated_at)}
            %li
              %strong= t('workarea.admin.fields.created_at')
              #{local_time_ago(model.created_at)}

          = link_to edit_payment_gift_card_path(model), class: 'card__button' do
            %span.button.button--small= t('workarea.admin.cards.attributes.button')

  .grid__cell
    .card{ class: card_classes(:redemptions, local_assigns[:active]) }
      = link_to payment_gift_card_redemptions_path(model), class: 'card__header' do
        %span.card__header-text= t('workarea.admin.payment_gift_cards.cards.redemptions.title')
        = inline_svg 'workarea/admin/icons/prices.svg', class: 'card__icon'

      - if local_assigns[:active].blank?
        .card__body
          - if model.redemptions.empty?
            %p= t('workarea.admin.payment_gift_cards.cards.redemptions.empty')
          - else
            %ul.list-reset
              - model.redemptions.take(10).each do |redemption|
                %li
                  %strong= redemption.order_id
                  = number_to_currency redemption.amount
                  #{local_time_ago(redemption.redeemed_at)}
              - if model.redemptions.size > 10
                %li= t('workarea.admin.cards.more', amount: model.redemptions.size - 10)
            = link_to payment_gift_card_redemptions_path(model), class: 'card__button' do
              %span.button.button--small= t('workarea.admin.payment_gift_cards.cards.redemptions.button')

  .grid__cell
    = render 'workarea/admin/timeline/card', timeline: model.timeline, active: local_assigns[:active]

  .grid__cell
    = render 'workarea/admin/comments/card', commentable: model, active: local_assigns[:active]

app/views/workarea/admin/payment_gift_cards/_menu.html.haml
- if Workarea::GiftCards.uses_system_cards?
  %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.gift_cards'), payment_gift_cards_path, class: navigation_link_classes(payment_gift_cards_path)

app/views/workarea/admin/payment_gift_cards/_summary.html.haml
.summary{ data: { global_id: model.to_global_id.to_param } }
  = link_to payment_gift_card_path(model, return_to: params[:return_to]) do
    %span.summary__name= model.name
    .summary__info-container
      %span.summary__info= local_time_ago(model.updated_at)
      %span.summary__info= number_to_currency model.amount
    %span.summary__type= t('workarea.admin.payment_gift_cards.gift_card')

  .summary__checkbox.hidden
    = check_box_tag 'product_id', model.to_global_id.to_param, false, class: 'summary__checkbox-input', id: dom_id(model)
    = label_tag dom_id(model), t('workarea.admin.bulk_actions.add_summary_button'), class: 'summary__checkbox-label'

app/views/workarea/admin/payment_gift_cards/edit.html.haml
- @page_title = t('workarea.admin.payment_gift_cards.edit.title', name: @gift_card.name)

.view
  .view__header
    .grid.grid--middle
      .grid__cell.grid__cell--25
        = render 'workarea/admin/releases/select'
      .grid__cell.grid__cell--50
        .view__heading
          = link_to_index_for(@gift_card)
          %h1= link_to @gift_card.name, url_for(@gift_card)
      .grid__cell.grid__cell--25
        = render_aux_navigation_for(@gift_card)

  .view__container
    = render_cards_for(@gift_card, :attributes)

  .view__container.view__container--narrow
    - if @gift_card.errors.present?
      - @gift_card.errors.full_messages.each do |message|
        = render_message 'error', message

    = form_tag payment_gift_card_path(@gift_card), method: 'patch', id: 'payment_gift_card_form' do
      = hidden_field_tag 'return_to', request.referrer

      .section
        .property
          = label_tag 'gift_card[to]', t('workarea.admin.fields.recipient'), class: 'property__name'
          = email_field_tag 'gift_card[to]', @gift_card.to, class: 'text-box'

        .property
          = label_tag 'gift_card[expires_at]', t('workarea.admin.fields.expires_on'), class: 'property__name'
          = datetime_picker_tag 'gift_card[expires_at]', @gift_card.expires_at, class: 'text-box', data: { datepicker_field: { inline: false } }

      .workflow-bar
        .grid.grid--auto.grid--right.grid--middle
          .grid__cell= button_tag t('workarea.admin.payment_gift_cards.edit.button'), value: 'save_gift_card', class: 'workflow-bar__button workflow-bar__button--create'

app/views/workarea/admin/payment_gift_cards/index.html.haml
- @page_title = t('workarea.admin.payment_gift_cards.index.title')

.view
  .view__header
    .grid.grid--middle.grid--center
      .grid__cell.grid__cell--50
        .view__heading
          = link_to "↑ #{t('workarea.admin.orders.index.dashboard_link')}", orders_dashboards_path, class: 'view__dashboard-button'
          %h1= t('workarea.admin.payment_gift_cards.index.title')

  .view__container
    .browsing-controls.browsing-controls--with-divider.browsing-controls--center{ class: ('browsing-controls--filters-displayed' unless @search.toggle_facets?) }
      = form_tag payment_gift_cards_path, method: 'get', id: 'gift_cards_form' do
        = facet_hidden_inputs(@search.facets)
        .browsing-controls__sort
          .property.property--inline
            = label_tag 'sort', t('workarea.admin.search.sort_by'), class: 'property__name'
            = select_tag :sort, options_for_select(@search.sorts, selected: @search.sort), data: { form_submitting_control: '' }

        .browsing-controls__search
          .search-form
            = text_field_tag :q, params[:q], class: 'search-form__input', id: 'search_products', title: t('workarea.admin.search.keywords'), placeholder: t('workarea.admin.search.keywords')
            = submit_tag 'search_gift_cards', class: 'search-form__button'

        = render 'workarea/admin/shared/creation_date', search: @search, form_path: payment_gift_cards_path

        - if @search.facets.present?
          - @search.facets.each do |facet|
            = render "workarea/admin/facets/#{facet.type}", facet: facet

        - if @search.toggle_facets?
          .browsing-controls__toggle-filters
            %button.text-button{ type: 'button', data: { toggle_filters: '' } }= t('workarea.admin.search.show_filters')

      = render 'workarea/admin/facets/applied', search: @search, reset_path: payment_gift_cards_path

      %p.browsing-controls__count{ data: { browsing_controls_count: @search.total } }
        = pluralize(@search.total, t('workarea.admin.payment_gift_cards.gift_card'))

    - if @search.results.any?
      %table.index-table
        %thead
          %tr
            %th.index-table__control-cell
              .checkbox
                = check_box_tag 'select_all', nil, false, id: 'select_all', class: 'checkbox__input', data: { bulk_action_select_all: '' }
                = label_tag 'select_all', t('workarea.admin.bulk_actions.select_all'), class: 'checkbox__label'
            %th= t('workarea.admin.fields.token')
            %th= t('workarea.admin.fields.from')
            %th= t('workarea.admin.fields.recipient')
            %th.align-right= t('workarea.admin.fields.amount')
            %th.align-right= t('workarea.admin.fields.balance')
            %th.align-center= t('workarea.admin.fields.order_id')
            %th.align-right= t('workarea.admin.fields.expires_on')
            %th= t('workarea.admin.fields.created_at')

        %tbody
          - @search.results.each do |result|
            %tr.index-table__row
              %td.index-table__control-cell
                .checkbox
                  = check_box_tag 'global_id', result.to_global_id.to_param, false, class: 'checkbox__input', id: dom_id(result), data: { bulk_action_item: '' }
                  = label_tag dom_id(result), '', class: 'checkbox__label', title: t('workarea.admin.bulk_actions.add_summary_button')
              %td
                = link_to result.token, payment_gift_card_path(result)
                = upcoming_changesets_icon_for(result)
                = comments_icon_for(result)
              %td= result.from.presence || t('workarea.admin.cards.attributes.no_value')
              %td= result.to
              %td.align-right= number_to_currency result.amount
              %td.align-right= number_to_currency result.balance
              %td.align-center= result.order_id.presence || t('workarea.admin.cards.attributes.no_value')
              %td.align-right
                - if result.expires_at.present?
                  = local_time_ago(result.expires_at)
                - else
                  = t('workarea.admin.cards.attributes.no_value')
              %td= local_time_ago(result.created_at)

      - if @search.results.total_pages > 1
        = render 'workarea/admin/shared/pagination', collection: @search.results

  .workflow-bar
    .grid
      .grid__cell.grid__cell--50
        = render 'workarea/admin/shared/bulk_actions', klass: Workarea::Payment::GiftCard, search: @search do
          .grid__cell
            = form_tag new_data_file_export_path, method: 'get', data: { bulk_action_form: '' } do
              = hidden_field_tag 'model_type', 'Workarea::Payment::GiftCard::Redemption', id: nil
              = hidden_field_tag 'query_id', @search.to_gid_param, id: nil
              = hidden_field_tag 'return_to', request.path, id: nil
              %button.workflow-bar__button{ type: :submit }= t('workarea.admin.payment_gift_cards.index.export_redemptions')

      .grid__cell.grid__cell--50.align-right
        = link_to t('workarea.admin.payment_gift_cards.index.button'), new_payment_gift_card_path, id: 'add_payment_gift_card', class: 'workflow-bar__button workflow-bar__button--create'

app/views/workarea/admin/payment_gift_cards/new.html.haml
- @page_title = t('workarea.admin.payment_gift_cards.new.title')

.view
  .view__header
    .grid.grid--middle.grid--center
      .grid__cell.grid__cell--50
        .view__heading
          = link_to_index_for(@gift_card)
          %h1= t('workarea.admin.payment_gift_cards.new.title')

  .view__container
    - if @gift_card.errors.present?
      - @gift_card.errors.full_messages.each do |message|
        = render_message 'error', message

    = form_tag payment_gift_cards_path, method: 'post', id: 'payment_gift_card_form' do
      = hidden_field_tag 'return_to', request.referrer

      .section
        .property
          = label_tag 'gift_card[token]', t('workarea.admin.fields.token'), class: 'property__name'
          = text_field_tag 'gift_card[token]', @gift_card.token, class: 'text-box'

        .property
          = label_tag 'gift_card[to]', t('workarea.admin.fields.recipient'), class: 'property__name'
          = email_field_tag 'gift_card[to]', @gift_card.to, class: 'text-box'

        .property
          = label_tag 'gift_card[notify]', t('workarea.admin.fields.notify'), class: 'property__name'
          = check_box_tag 'gift_card[notify]', 1, false

        .property
          = label_tag 'gift_card[amount]', t('workarea.admin.fields.amount'), class: 'property__name'
          %span $
          = text_field_tag 'gift_card[amount]', @gift_card.amount, class: 'text-box text-box--small'

        .property
          = label_tag 'gift_card[expires_at]', t('workarea.admin.fields.expires_on'), class: 'property__name'
          = datetime_picker_tag 'gift_card[expires_at]', @gift_card.expires_at, class: 'text-box', data: { datepicker_field: { inline: false } }

      .workflow-bar
        .grid.grid--auto.grid--right.grid--middle
          .grid__cell= button_tag t('workarea.admin.payment_gift_cards.new.button'), value: 'create_gift_card', class: 'workflow-bar__button workflow-bar__button--create'

app/views/workarea/admin/payment_gift_cards/redemptions.html.haml
- @page_title = t('workarea.admin.payment_gift_cards.redemptions.title', name: @gift_card.name)

.view
  .view__header
    .grid.grid--middle.grid--center
      .grid__cell.grid__cell--50
        .view__heading
          = link_to_index_for(@gift_card)
          %h1= link_to @gift_card.name, url_for(@gift_card)

  .view__container
    = render_cards_for(@gift_card, :redemptions)

  .view__container
    %p.align-center= pluralize(@gift_card.redemptions.count, t('workarea.admin.payment_gift_cards.redemptions.redemption'))

    - if @gift_card.redemptions.any?
      %table
        %thead
          %tr
            %th= t('workarea.admin.fields.order_id')
            %th= t('workarea.admin.fields.amount')
            %th= t('workarea.admin.fields.redeemed_at')
        %tbody
          - @gift_card.redemptions.each do |redemption|
            %tr
              %td= link_to redemption.order_id, order_path(redemption.order_id)
              %td= number_to_currency redemption.amount
              %td= local_time(redemption.redeemed_at, :long)

app/views/workarea/admin/payment_gift_cards/show.html.haml
- @page_title = @gift_card.name

.view
  .view__header
    .grid.grid--middle
      .grid__cell.grid__cell--25
        = render 'workarea/admin/releases/select'
      .grid__cell.grid__cell--50
        .view__heading
          = link_to_index_for(@gift_card)
          %h1= @gift_card.name
      .grid__cell.grid__cell--25
        = render_aux_navigation_for(@gift_card)

  .view__container
    = render_cards_for(@gift_card)

    .workflow-bar
      = link_to t('workarea.admin.actions.delete'), payment_gift_card_path(@gift_card), class: 'workflow-bar__button workflow-bar__button--delete', data: { method: 'delete', confirm: t('workarea.admin.actions.delete_confirmation') }